services:
  # Frontend service only
  - type: web
    name: fruitzone-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://server-orcin-beta.vercel.app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
